name: Sync & Build Podman from Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # ogni giorno alle 3:00 UTC

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout empty action repo (forked)
        uses: actions/checkout@v4

      - name: Fetch latest release tag from upstream
        id: get_tag
        run: |
          tag=$(curl -s https://api.github.com/repos/containers/podman/releases/latest | jq -r .tag_name)
          echo "Ultima release: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Clone Podman upstream source at tag
        run: |
          git clone --depth 1 --branch ${{ steps.get_tag.outputs.tag }} https://github.com/containers/podman.git source

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libseccomp-dev \
            libapparmor-dev \
            libgpgme-dev \
            btrfs-progs \
            libbtrfs-dev \
            pkg-config \
            make \
            git

      - name: Compile Podman
        working-directory: ./source
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          make clean
          make BUILDTAGS="seccomp apparmor" binaries
          mkdir -p ../dist/${{ matrix.arch }}
          cp bin/podman ../dist/${{ matrix.arch }}/podman

      - name: Create tar.gz
        run: |
          cd dist/${{ matrix.arch }}
          tar -czf ../../podman-${{ matrix.arch }}-${{ steps.get_tag.outputs.tag }}.tar.gz podman

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: podman-${{ matrix.arch }}
          path: podman-${{ matrix.arch }}-${{ steps.get_tag.outputs.tag }}.tar.gz

      - name: Publish to release (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: podman-*.tar.gz
